openapi: 3.0.1
info:
  title: Event Management System API
  description: Event Management System
  contact:
    email: nadeem.p.j@gmail.com
  version: v1
servers:
- url: http://localhost:8000/api/

security:
  - 
    jwtToken: []
# - bearerAuth: []
paths:
  /login/:
    post:
      tags:
      - Login
      description: Takes a set of user credentials and returns a token to prove the authentication of those credentials.
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
        required: true
      responses:
        200:
          description: "login"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
        400:
          description: User doesn't exist 
      x-codegen-request-body-name: data          
  /events/:
    get:
      tags:
      - Events
      operationId: event_list
      responses:
        200:
          description: Fetch all events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/eventDetailsList'
    post:
      tags:
      - Events
      description:  Create events API
      operationId: event_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/event'
        required: true
      responses:
        200:
          description: "create event"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/eventDetails'
      x-codegen-request-body-name: data
  /events/{id}:
    get:
      tags:
      - Events
      operationId: event_fetch
      responses:
        200:
          description: Fetch all events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/eventDetails'
    patch:
      tags:
      - Events
      description:  Update events API
      operationId: event_update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/event'
        required: true
      responses:
        200:
          description: "update event"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/eventDetails'
  
  /tickets/:
    get:
      tags:
      - Tickets
      operationId: ticket_list
      responses:
        200:
          description: Fetch all tickets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ticketDetailsList'
    post:
      tags:
      - Tickets
      description:  Buy ticket API
      operationId: ticket_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ticket'
        required: true
      responses:
        200:
          description: "create ticket"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ticketDetails'
      x-codegen-request-body-name: data
    
  /ticket/{id}:
    get:
      tags:
      - Tickets
      operationId: ticket_fetch
      responses:
        200:
          description: Fetch ticket
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ticketDetails'
                
  
  /users/:
    post:
      tags:
      - Tickets
      description: Create user API
      operationId: user_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
        required: true
      responses:
        200:
          description: "create user"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userDetails'
      x-codegen-request-body-name: data

components:
  securitySchemes:
        jwtToken:
            scheme: bearer
            type: http
  schemas:
    
    login:
      required:
      - username
      - password
      type: object
      properties:
        username:
          title: Username
          type: string
          nullable: false
        password:
          title: Password
          type: string
          nullable: false
          
    token:
      type: object
      properties:
        token:
          title: Token
          type: string
    
    event:
      required:
      - name
      - seats_count
      - booking_window
      - date
      type: object
      properties:
        name:
          title: Name
          type: string
          nullable: false
        seats_count:
          title: Seats count
          type: integer
          nullable: false
        booking_window:
          title: Booking window
          type: integer
          nullable: false
        date:
          title: Date of event
          type: string
          nullable: false
        venue:
          title: Venue
          type: string
          nullable: false
    
    eventDetails:
      type: object
      properties:
        id:
          title: Id
          type: integer
        creator:
          title: Creator
          type: string
        updator:
          title: Updator
          type: string
        created_date:
          title: Created date
          type: string
        updated_date:
          title: Created date
          type: string
        name:
          title: Name
          type: string
        date:
          title: Date
          type: string
        venue:
          title: Venue
          type: string
        seats_count:
          title: Seats count
          type: integer
        booking_window:
          title: Booking window
          type: integer
          
    eventDetailsList:
      type: array
      items: 
        type: object
        properties:
          id:
            title: Id
            type: integer
          creator:
            title: Creator
            type: string
          updator:
            title: Updator
            type: string
          created_date:
            title: Created date
            type: string
          updated_date:
            title: Created date
            type: string
          name:
            title: Name
            type: string
          date:
            title: Date
            type: string
          venue:
            title: Venue
            type: string
          seats_count:
            title: Seats count
            type: integer
          booking_window:
            title: Booking window
            type: integer
            
    ticket:
      required:
      - seat_number
      - event
      - user
      type: object
      properties:
        seat_number:
          title: Seat number
          type: integer
          nullable: false
        event:
          title: Event
          type: integer
          nullable: false
        user:
          title: User
          type: integer
          nullable: false
        
    ticketDetails:
      type: object
      properties:
        id:
          title: Id
          type: integer
        seat_number:
          title: Seat Number
          type: integer
        user:
          title: User
          type: integer
        event:
          title: Event
          type: object
          properties:
            id:
              title: Id
              type: integer
            creator:
              title: Creator
              type: string
            updator:
              title: Updator
              type: string
            created_date:
              title: Created date
              type: string
            updated_date:
              title: Created date
              type: string
            name:
              title: Name
              type: string
            date:
              title: Date
              type: string
            venue:
              title: Venue
              type: string
            seats_count:
              title: Seats count
              type: integer
            booking_window:
              title: Booking window
              type: integer  
    
    ticketDetailsList:
      type: array
      items:
        type: object
        properties:
          id:
            title: Id
            type: integer
          seat_number:
            title: Seat Number
            type: integer
          user:
            title: User
            type: integer
          event:
            title: Event
            type: object
            properties:
              id:
                title: Id
                type: integer
              creator:
                title: Creator
                type: string
              updator:
                title: Updator
                type: string
              created_date:
                title: Created date
                type: string
              updated_date:
                title: Created date
                type: string
              name:
                title: Name
                type: string
              date:
                title: Date
                type: string
              venue:
                title: Venue
                type: string
              seats_count:
                title: Seats count
                type: integer
              booking_window:
                title: Booking window
                type: integer  
                
    user:
      required:
      - first_name
      - last_name
      - username
      - password
      - groups
      - email
      type: object
      properties:
        first_name:
          title: First name
          type: string
          nullable: false
        last_name:
          title: Last name
          type: string
          nullable: false
        username:
          title: Username
          type: string
          nullable: false
        password:
          title: password
          type: string
          nullable: false
        groups:
          title: Groups
          type: integer
          nullable: false
        email:
          title: Email
          type: string
          nullable: false
          
    userDetails:
      type: object
      properties:
        first_name:
          title: First name
          type: string
        last_name:
          title: Last name
          type: string
        username:
          title: Username
          type: string
        password:
          title: password
          type: string
        groups:
          title: Groups
          type: integer
        email:
          title: Email
          type: string